### ISSUE TITLE
NullPointerException on the create() method

### ISSUE THREAD

**Issue by TornadoOfSoup** [Samuel-Maddock/StrawPoll-Java-API#1]
Hey,

Has anything changed about the StrawPoll API since this was last updated? I get NullPointerExceptions from the create(), update(), and retrieve() methods, all of which seem to stem from the retrieve() method. These exceptions occur even when running example code. 

Thanks.

**Comment by Samuel-Maddock** [comment]
Thanks for letting me know, I think I've fixed the issue now. Let me know if you encounter any other errors.
