### ISSUE TITLE
update() throws a NullPointerException

### ISSUE THREAD

**Issue by TornadoOfSoup** [Samuel-Maddock/StrawPoll-Java-API#2]
Thanks for fixing the things before, everything I need works now.
Aside from that, there are a few small things. 
the update() method still seems to throw an error, though I don't need to use it.
There's one thing in your tutorial where you do something like StrawPoll poll = new poll(); which isn't correct.
I had my own mistake when I was retrieving polls in which I was passing it the poll id in a String form, which isn't really a problem on your end but it might help to clarify that a bit.

Thanks again for helping out.

**Comment by Samuel-Maddock** [comment]
Thanks for spotting the mistakes, I've fixed the README. You're right about the update() bug, I forgot to change it along with the create() method in the earlier version so I've also fixed that. Update to 1.0.3 and it should be fine.

I've also added some more documentation to the methods in the StrawPoll.java file which you can check out which should clarify some of the issues with things like passing the id in String form when it needs to be an int.

Thanks!
